// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9mbuQJvq5C5cqi8SqHy6B4mQ1s_3XNdQ',
    appId: '1:962264114555:web:2e2b0aacfa5b0a4d6189de',
    messagingSenderId: '962264114555',
    projectId: 'meals-b75d1',
    authDomain: 'meals-b75d1.firebaseapp.com',
    storageBucket: 'meals-b75d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWFoSyK2XMWq7lqzZb1fzYpP3cg87qsKY',
    appId: '1:962264114555:android:2b18cbb6f647ef346189de',
    messagingSenderId: '962264114555',
    projectId: 'meals-b75d1',
    storageBucket: 'meals-b75d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc1yLykmx2jKpAD_yVNNOirDCoNjkVkPE',
    appId: '1:962264114555:ios:ab5afa968e77c9f96189de',
    messagingSenderId: '962264114555',
    projectId: 'meals-b75d1',
    storageBucket: 'meals-b75d1.appspot.com',
    iosBundleId: 'com.example.meals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc1yLykmx2jKpAD_yVNNOirDCoNjkVkPE',
    appId: '1:962264114555:ios:c729613894a3da1c6189de',
    messagingSenderId: '962264114555',
    projectId: 'meals-b75d1',
    storageBucket: 'meals-b75d1.appspot.com',
    iosBundleId: 'com.example.meals.RunnerTests',
  );
}
